# Generated by Django 5.0.4 on 2024-04-08 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=30)),
                ('portfolio_link', models.CharField(max_length=100)),
                ('skills', models.CharField(choices=[('1', 'Python'), ('2', 'JavaScript'), ('3', 'CSS')], default='1', max_length=1, verbose_name='Skills')),
                ('is_developer', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
