# Generated by Django 5.0.4 on 2024-04-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepal_app', '0004_remove_profile_roles_profile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.BooleanField(verbose_name='Follow Me?')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Followed', to='codepal_app.profile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to='codepal_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(verbose_name='Did you like project?')),
                ('liked_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_liked', to='codepal_app.project')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='codepal_app.profile')),
            ],
        ),
    ]
