# Generated by Django 5.0.4 on 2024-04-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codepal_app', '0005_follow_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_following',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
