# Generated by Django 5.0.4 on 2024-04-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepal_app', '0006_remove_follow_is_following_remove_like_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portfolio_link',
            field=models.URLField(max_length=1000, verbose_name='Portfolio Link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(max_length=1000, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
