# Generated by Django 5.0.4 on 2024-04-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codepal_app', '0007_alter_profile_portfolio_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
