# Generated by Django 5.0.4 on 2024-04-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepal_app', '0009_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portfolio_link',
            field=models.CharField(max_length=1000, verbose_name='Portfolio Link'),
        ),
    ]
