# Generated by Django 5.0.4 on 2024-04-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codepal_app', '0010_alter_profile_portfolio_link'),
        ('codepal_app', '0010_rename_user_project_profile'),
    ]

    operations = [
    ]
